### ISSUE TITLE
make this module ZF3 compatible

### ISSUE THREAD

**Issue by cbleek** [yawik/CompanyRegistration#1]
@TiSiE please invite toni to do this task and create issues for the other modules used by the Demo.

**Comment by cbleek** [comment]
hi @kilip,

this module modiefies the regstration form. Pleas make sure, that it works with ZF3

Dos: http://yawik.readthedocs.io/en/latest/modules/company-registration/index.html#

**Comment by kilip** [comment]
hi @cbleek, I am start working on this module now.

**Comment by cbleek** [comment]
was done in https://github.com/yawik/CompanyRegistration/pull/2/commits/c381f682332928a1e31cdd2a53dc331fd14097f5
